### ISSUE TITLE
Erro 500

### ISSUE THREAD

**Issue by Suburbanno** [pyanderson/gather-scrobble#2]
Gerei novas chaves e sem sucesso, segue o log

@pyanderson 

```bash
@Suburbanno ➜ /workspaces/gather-scrobble (main) $ gather-scrobble start <spaceid> -v
[2024-07-27 18:30:52,614][DEBUG] Loading credentials
[2024-07-27 18:30:52,788][DEBUG] Starting application
[2024-07-27 18:30:53,310][INFO] Connected to wss://ip-10-204-111-147.sa-east-1-a.prod.aws.gather.town:443/
[2024-07-27 18:30:53,689][INFO] Connected as user <user>
[2024-07-27 18:30:53,690][DEBUG] Receiving messages
[2024-07-27 18:30:53,690][DEBUG] Heartbeat sent
[2024-07-27 18:30:53,690][DEBUG] Application started
[2024-07-27 18:30:53,823][DEBUG] New Status: 🎸 - I like the way you kiss me - Artemas
[2024-07-27 18:30:54,354][DEBUG] Message received: events {
  error {
    message: "error processing action setEmojiStatus: TypeError: Cannot read properties of undefined (reading \'autoPromoteMembersEmailDomains\')"
    code: 500
  }
}
events {
  transactionStatus {
    txnId: 2130860465
    reason: "error processing action setEmojiStatus: TypeError: Cannot read properties of undefined (reading \'autoPromoteMembersEmailDomains\')"
  }
}
events {
  error {
    message: "error processing action setTextStatus: TypeError: Cannot read properties of undefined (reading \'autoPromoteMembersEmailDomains\')"
    code: 500
  }
}
events {
  transactionStatus {
    txnId: 4250963392
    reason: "error processing action setTextStatus: TypeError: Cannot read properties of undefined (reading \'autoPromoteMembersEmailDomains\')"
  }
}

[2024-07-27 18:31:03,724][DEBUG] Message received: events {
  serverHeartbeat {
    lastRTT: 4118135364
  }
}
```bash

**Comment by pyanderson** [comment]
Ei @Suburbanno, isso parece ser um problema com o Gather, provavelmente é algum problema com a configuração do espaço que você está usando, eu criei um tópico reportando esse problema no fórum do Gather para ver se alguém consegue ajudar: https://forum.gather.town/t/error-processing-action-settextstatus/807

**Comment by Suburbanno** [comment]
> Ei @Suburbanno, isso parece ser um problema com o Gather, provavelmente é algum problema com a configuração do espaço que você está usando, eu criei um tópico reportando esse problema no fórum do Gather para ver se alguém consegue ajudar: https://forum.gather.town/t/error-processing-action-settextstatus/807

Valeu Anderson, vou acompanhar o fórum!

**Comment by pyanderson** [comment]
Hey @Suburbanno aparentemente o problema foi resolvido, dá uma olhadinha:

https://forum.gather.town/t/error-processing-action-settextstatus/807/3

**Comment by Suburbanno** [comment]
> Hey @Suburbanno aparentemente o problema foi resolvido, dá uma olhadinha:
> 
> https://forum.gather.town/t/error-processing-action-settextstatus/807/3

Boa tarde!

Gerei novas credenciais e agora está dando erro 400.

```bash
events {
  error {
    message: "Player not found: VFC6y1NmnoXwlVbdxxI20NKaxxx"
    code: 400
  }
}
```

**Comment by pyanderson** [comment]
> > Hey @Suburbanno aparentemente o problema foi resolvido, dá uma olhadinha:
> > https://forum.gather.town/t/error-processing-action-settextstatus/807/3
> 
> Boa tarde!
> 
> Gerei novas credenciais e agora está dando erro 400.
> 
> ```shell
> events {
>   error {
>     message: "Player not found: VFC6y1NmnoXwlVbdxxI20NKaxxx"
>     code: 400
>   }
> }
> ```

O espaço que você gerou as credenciais é o mesmo espaço que você está usando para executar o scrobble?

**Comment by Suburbanno** [comment]
> > > Hey @Suburbanno aparentemente o problema foi resolvido, dá uma olhadinha:
> > > https://forum.gather.town/t/error-processing-action-settextstatus/807/3
> > 
> > 
> > Boa tarde!
> > Gerei novas credenciais e agora está dando erro 400.
> > ```shell
> > events {
> >   error {
> >     message: "Player not found: VFC6y1NmnoXwlVbdxxI20NKaxxx"
> >     code: 400
> >   }
> > }
> > ```
> 
> O espaço que você gerou as credenciais é o mesmo espaço que você está usando para executar o scrobble?

Estou apenas em um espaço virtual, não sou admin, apenas usuário comum nele.

Fiz um espaço para testes onde sou admin, o resultado é o mesmo.

Tem como escolher o espaço que irá gerar a key? no site existe apenas um botão de gerar ou revogar.

**Comment by pyanderson** [comment]
Verdade, não tem como. A chave é por usuário. Acho que você precisa reportar esse novo erro lá no fórum.

**Comment by Suburbanno** [comment]
Vou fechar a issue, o time do gather não tem lá boa vontade em ajudar, nesse caso desisti de fazer o uso. Valeu!
